Tricrypto `remove_liquidity_one_coin` and `remove_liquidity`
curveresearch/curvesim pull request #283
Opened 2023-11-08 17:09 UTC by allt0ld

### Description

Closes #218.

- Made `CurveCryptoPool`'s `remove_liquidity` and `remove_liquidity_one_coin` functions work for 3-coin pools.
- New tests `test_remove_liquidity` and `test_remove_liquidity_one_coin` in `test_tricrypto.py` are borrowed directly from `test_cryptopool.py`.

### Hygiene checklist

- [x] Changelog entry
- [x] Everything public has a Numpy-style docstring
      (modules, public functions, classes, and public methods)
- [x] Commit history is cleaned-up with minor changes squashed together
      and descriptive commit messages following [Tim Pope's style](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)

### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->](https://imgs.search.brave.com/m8JcE8u8nNUZ8Q-WRivqApBts88NYUd8WRnmO0kwbGc/rs:fit:860:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzAwLzM0LzAyLzgz/LzM2MF9GXzM0MDI4/MzcyX096Ykd4VkdZ/b3NWd2ZQeUI1RmdN/NVVtbXh6TFVEQVlS/LmpwZw)

2023-11-08 22:56 UTC, nagakingg commented on test/unit/test_tricrypto.py
> +@given(lp_tokens, st.integers(min_value=0, max_value=1))
Unlikely to matter, but max_value should be 2, right?

2023-11-09 21:30 UTC, chanhosuh requested changes

2023-11-09 21:30 UTC, chanhosuh commented on curvesim/pool/cryptoswap/pool.py
> +        d_balances: List[int] = [0] * n_coins
i would call this something more readable like `withdraw_amounts`.

2023-11-09 21:30 UTC, chanhosuh commented on curvesim/pool/cryptoswap/pool.py
> +            A, gamma, token_amount, i, False, calc_price
nice!

2023-11-09 21:30 UTC, chanhosuh commented on test/unit/test_tricrypto.py
> +    assume(amount < vyper_tricrypto.totalSupply())
let's test the edge case of when amount is total supply

2023-11-09 21:30 UTC, chanhosuh commented on test/unit/test_tricrypto.py
> +    expected_coin_balance = vyper_tricrypto.balances(i)
we might as well check all the balances to make sure something weird didn't happen.

2023-11-10 18:41 UTC, chanhosuh approved these changes

2023-11-10 18:41 UTC, merged